baseurl: /
url: unmaya.github.io

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

exclude: [scss, scripts, images, components, grunt_settings, node_modules, Gruntfile.js, package.json, component.json, bower.json, Gemfile, Gemfile.lock, README.md]

author: Fred Maya
description: UX / UI Design
twitter: unmaya
github: unmaya
