baseurl: /
url: comfypixel.com

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

exclude: [scss, scripts, images, components, grunt_settings, node_modules, Gruntfile.js, package.json, component.json, bower.json, Gemfile, Gemfile.lock, README.md, *.sublime-project, *.sublime-workspace]

author: Fred Maya
description: Comfy Pixel. Interaction Design, Information Architecture and User Experience.
twitter: unmaya
github: unmaya
tumblr: unsurreal.com
google_analytics_id: UA-272608-12
